logger:
  file:
    path: /var/log/open5gs/sgwu.log

global:
  max:
    ue: 1024

sgwu:
  pfcp:
    server:
      - address: 10.44.44.3
  gtpu:
    server:
      - dev: eth0
        advertise: docker-host.external-ip  # 通过 extra_hosts 映射到宿主机外网 IP，给 eNB 用