logger:
  file:
    path: /var/log/open5gs/smf.log
  level: debug

global:

smf:
  freeDiameter: /etc/freeDiameter/smf.conf
  sbi:
    server:
      - address: 10.44.44.4
        port: 80
    client:
      nrf:
        - uri: http://10.44.44.7:80
  pfcp:
    server:
      - address: 10.44.44.4
    client:
      upf:
        - address: 10.44.44.6
  gtpu:
    server:
      - address: 10.44.44.4
  gtpc:
    server:
      - address: 10.44.44.4
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
