logger:
  file:
    path: /var/log/open5gs/upf.log
  level: debug  # fatal|error|warn|info(default)|debug|trace

global:

upf:
  pfcp:
    server:
      - address: 10.44.44.6
    client:
  gtpu:
    server:
      - address: 10.44.44.6
        advertise: docker-host.external-ip
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
